export const seedDevices = [
  { id: 'd1', name: 'LED Bulb', category: 'electronics', watts: 10, tags: ['basic', 'lighting'] },
  { id: 'd2', name: 'Standing Fan', category: 'motor', watts: 50, tags: ['cooling', 'essential'] },
  { id: 'd3', name: 'Ceiling Fan', category: 'motor', watts: 75, tags: ['cooling', 'essential'] },
  { id: 'd4', name: 'Laptop', category: 'electronics', watts: 65, tags: ['study', 'office'] },
  { id: 'd5', name: 'Wi-Fi Router', category: 'electronics', watts: 15, tags: ['internet', 'essential'] },
  { id: 'd6', name: 'Phone Charger', category: 'electronics', watts: 10, tags: ['basic', 'essential'] },
  { id: 'd7', name: 'Studio Monitor (Speaker)', category: 'electronics', watts: 40, tags: ['studio', 'audio'] },
  { id: 'd8', name: 'Desktop PC', category: 'electronics', watts: 200, tags: ['office', 'gaming'] },
  { id: 'd9', name: 'Refrigerator (Small)', category: 'compressor', watts: 120, tags: ['kitchen', 'essential'] },
  { id: 'd10', name: 'Air Conditioner (1HP)', category: 'compressor', watts: 850, tags: ['luxury', 'office'] },
  { id: 'd11', name: 'Television (43")', category: 'electronics', watts: 80, tags: ['entertainment'] },
  { id: 'd12', name: 'Huawei B818-263', category: 'internet', watts: 20, tags: ['internet', 'tier-a'] },
  { id: 'd13', name: 'ZTE MC888', category: 'internet', watts: 25, tags: ['internet', 'tier-a'] },
  { id: 'd14', name: 'ZTE MC888 PRO', category: 'internet', watts: 30, tags: ['internet', 'tier-a'] },
  { id: 'd15', name: 'Huawei CPE PRO 2', category: 'internet', watts: 22, tags: ['internet', 'tier-a'] },
  { id: 'd16', name: 'Cudy LT500', category: 'internet', watts: 12, tags: ['internet', 'tier-b'] },
  { id: 'd17', name: 'Cudy LT700', category: 'internet', watts: 15, tags: ['internet', 'tier-b'] },
  { id: 'd18', name: 'TP-Link ER605', category: 'internet', watts: 15, tags: ['internet', 'tier-b'] },
  { id: 'd19', name: 'TP-Link ER7206', category: 'internet', watts: 20, tags: ['internet', 'tier-b'] },
  { id: 'd20', name: 'Starlink Gen 2', category: 'internet', watts: 65, tags: ['internet', 'flagship'] },
  { id: 'd21', name: 'Starlink Gen 3', category: 'internet', watts: 85, tags: ['internet', 'flagship'] },
  { id: 'd22', name: 'GL.iNet Spitz AX', category: 'internet', watts: 18, tags: ['internet', 'router'] },
  { id: 'd23', name: 'GL.iNet Slate AX', category: 'internet', watts: 15, tags: ['internet', 'router'] },
  { id: 'd24', name: 'Cudy WR2100', category: 'internet', watts: 12, tags: ['internet', 'router'] },
  { id: 'd25', name: 'Pepwave MAX BR1 Mini', category: 'internet', watts: 20, tags: ['internet', 'enterprise'] },
];

export const seedProducts = [
  {
    id: 'p1',
    name: 'SolarOne A300 Plug-and-Play Power Box',
    description: 'True plug-and-play "Setup in a Box" - unbox, plug in, and power up with zero installation labor fees.',
    type: 'combination',
    combination_data: {
      inverter: '300W Pure Sine Wave',
      inverter_w: 300,
      battery_config: '390Wh Deep Cycle',
      battery_wh: 390,
      panel_config: '1x 250W Mono',
      panel_w: 250,
      total_price: 185000,
      status: 'Optimal',
      advice: 'Perfect for exams and studio sessions.',
      kit_type: 'solar',
      product_name: 'SolarOne A300 Plug-and-Play Power Box',
      product_description: 'True plug-and-play "Setup in a Box" - unbox, plug in, and power up with zero installation labor fees.',
      component_specs: [
        { role: 'inverter', name: '300W Pure Sine Wave', quantity: 1, specs: { watts: 300 } },
        { role: 'battery', name: '390Wh Deep Cycle', quantity: 1, specs: { usable_wh: 390 } },
        { role: 'panel', name: '1x 250W Mono', quantity: 1, specs: { watts: 250 } },
      ],
    },
    tags: ['flagship', 'kit', 'powerstation', 'solar'],
    price: 185000,
  },
  {
    id: 'p2',
    name: 'SolarOne A500 Pro Power Box',
    description: 'Whole-house power without the installation: custom generator-style outlet plugs directly into your home wiring.',
    type: 'combination',
    combination_data: {
      inverter: '500W Pure Sine Wave',
      inverter_w: 500,
      battery_config: '600Wh LiFePO4',
      battery_wh: 600,
      panel_config: '1x 350W Mono',
      panel_w: 350,
      total_price: 300000,
      status: 'Optimal',
      advice: 'Premium power for sensitive electronics.',
      kit_type: 'solar',
      product_name: 'SolarOne A500 Pro Power Box',
      product_description: 'Whole-house power without the installation: custom generator-style outlet plugs directly into your home wiring.',
      component_specs: [
        { role: 'inverter', name: '500W Pure Sine Wave', quantity: 1, specs: { watts: 500 } },
        { role: 'battery', name: '600Wh LiFePO4', quantity: 1, specs: { usable_wh: 600 } },
        { role: 'panel', name: '1x 350W Mono', quantity: 1, specs: { watts: 350 } },
      ],
    },
    tags: ['flagship', 'kit', 'powerstation', 'solar'],
    price: 300000,
  },
  {
    id: 'p3',
    name: 'Itel Energy iESS 320T + 200W Panel Kit',
    description: 'True plug-and-play setup: 130W pure sine wave inverter and 320Wh LiFePO4 battery in a compact, portable case.',
    type: 'combination',
    combination_data: {
      inverter: '130W Pure Sine Wave',
      inverter_w: 130,
      battery_config: '320Wh LiFePO4',
      battery_wh: 320,
      panel_config: '1x 200W Mono',
      panel_w: 200,
      total_price: 185000,
      status: 'Optimal',
      advice: 'Built for students. Direct laptop charging via Type-C.',
      kit_type: 'solar',
      product_name: 'Itel Energy iESS 320T + 200W Panel Kit',
      product_description: 'True plug-and-play setup: 130W pure sine wave inverter and 320Wh LiFePO4 battery in a compact, portable case.',
      component_specs: [
        { role: 'inverter', name: '130W Pure Sine Wave', quantity: 1, specs: { watts: 130 } },
        { role: 'battery', name: '320Wh LiFePO4', quantity: 1, specs: { usable_wh: 320 } },
        { role: 'panel', name: '1x 200W Mono', quantity: 1, specs: { watts: 200 } },
      ],
    },
    tags: ['solar', 'kit', 'powerstation'],
    price: 185000,
  },
  {
    id: 'p4',
    name: 'Itel 1000W Powerstation + 450W Panel',
    description: 'Massive 1000Wh LiFePO4 battery paired with a 500W pure sine wave inverter for clean, stable studio power.',
    type: 'combination',
    combination_data: {
      inverter: '500W Pure Sine Wave',
      inverter_w: 500,
      battery_config: '1000Wh LiFePO4',
      battery_wh: 1000,
      panel_config: '1x 450W Mono',
      panel_w: 450,
      total_price: 425000,
      status: 'Optimal',
      advice: 'Complete one-stop solution for studio power.',
      kit_type: 'solar',
      product_name: 'Itel 1000W Powerstation + 450W Panel',
      product_description: 'Massive 1000Wh LiFePO4 battery paired with a 500W pure sine wave inverter for clean, stable studio power.',
      component_specs: [
        { role: 'inverter', name: '500W Pure Sine Wave', quantity: 1, specs: { watts: 500 } },
        { role: 'battery', name: '1000Wh LiFePO4', quantity: 1, specs: { usable_wh: 1000 } },
        { role: 'panel', name: '1x 450W Mono', quantity: 1, specs: { watts: 450 } },
      ],
    },
    tags: ['solar', 'kit', 'powerstation'],
    price: 425000,
  },
  {
    id: 'p5',
    name: '500W Powerstation + 350W Panel Combo',
    description: 'Accessible off-grid power featuring a 600Wh LiFePO4 battery and 500W modified sine wave AC output.',
    type: 'combination',
    combination_data: {
      inverter: '500W Modified Sine',
      inverter_w: 500,
      battery_config: '600Wh LiFePO4',
      battery_wh: 600,
      panel_config: '1x 350W Mono',
      panel_w: 350,
      total_price: 310000,
      status: 'Optimal',
      advice: 'Accessible off-grid power for daily essentials.',
      kit_type: 'solar',
      product_name: '500W Powerstation + 350W Panel Combo',
      product_description: 'Accessible off-grid power featuring a 600Wh LiFePO4 battery and 500W modified sine wave AC output.',
      component_specs: [
        { role: 'inverter', name: '500W Modified Sine', quantity: 1, specs: { watts: 500 } },
        { role: 'battery', name: '600Wh LiFePO4', quantity: 1, specs: { usable_wh: 600 } },
        { role: 'panel', name: '1x 350W Mono', quantity: 1, specs: { watts: 350 } },
      ],
    },
    tags: ['solar', 'kit', 'powerstation'],
    price: 310000,
  },
  {
    id: 'p_int_2',
    name: 'Budget Dual Stack Internet Kit',
    description: 'Two-network redundancy. Cudy CPE on MTN + Android phone tether on Airtel.',
    type: 'combination',
    combination_data: {
      inverter: 'Load Balancing Router',
      inverter_w: 10,
      battery_config: 'N/A',
      battery_wh: 0,
      panel_config: 'N/A',
      panel_w: 0,
      total_price: 135000,
      status: 'Optimal',
      advice: 'The cheapest genuine failover setup for remote workers.',
      kit_type: 'internet',
      product_name: 'Budget Dual Stack Internet Kit',
      product_description: 'Two-network redundancy. Cudy CPE on MTN + Android phone tether on Airtel.',
      component_specs: [{ role: 'network', name: 'Budget Dual Stack Internet Kit', quantity: 1, specs: { watts: 10 } }],
    },
    tags: ['internet', 'kit'],
    price: 135000,
  },
  {
    id: 'p_int_3',
    name: 'Standard Dual CPE Internet Kit',
    description: 'Full reliability. Huawei B818 (MTN) + Cudy LT500 (Airtel) + TP-Link ER605.',
    type: 'combination',
    combination_data: {
      inverter: 'TP-Link ER605 Load Balancer',
      inverter_w: 15,
      battery_config: 'N/A',
      battery_wh: 0,
      panel_config: 'N/A',
      panel_w: 0,
      total_price: 235000,
      status: 'Optimal',
      advice: 'Two router-grade CPE devices for full signal quality.',
      kit_type: 'internet',
      product_name: 'Standard Dual CPE Internet Kit',
      product_description: 'Full reliability. Huawei B818 (MTN) + Cudy LT500 (Airtel) + TP-Link ER605.',
      component_specs: [{ role: 'network', name: 'Standard Dual CPE Internet Kit', quantity: 1, specs: { watts: 15 } }],
    },
    tags: ['internet', 'kit'],
    price: 235000,
  },
  {
    id: 'p_int_5',
    name: 'Dual CPE Pro Internet Kit',
    description: 'High capacity 5G primary (ZTE MC888 Pro) + 4G secondary (Huawei B818).',
    type: 'combination',
    combination_data: {
      inverter: 'TP-Link ER605 Load Balancer',
      inverter_w: 20,
      battery_config: 'N/A',
      battery_wh: 0,
      panel_config: 'N/A',
      panel_w: 0,
      total_price: 310000,
      status: 'Optimal',
      advice: 'MTN 5G primary reaches 60-100Mbps in strong coverage areas.',
      kit_type: 'internet',
      product_name: 'Dual CPE Pro Internet Kit',
      product_description: 'High capacity 5G primary (ZTE MC888 Pro) + 4G secondary (Huawei B818).',
      component_specs: [{ role: 'network', name: 'Dual CPE Pro Internet Kit', quantity: 1, specs: { watts: 20 } }],
    },
    tags: ['internet', 'kit'],
    price: 310000,
  },
  {
    id: 'p_int_6',
    name: 'Bonded Stack Internet Kit',
    description: 'True packet-level bonding. Speedify + Dual CPE Pro hardware.',
    type: 'combination',
    combination_data: {
      inverter: 'Bonding Engine',
      inverter_w: 20,
      battery_config: 'N/A',
      battery_wh: 0,
      panel_config: 'N/A',
      panel_w: 0,
      total_price: 310000,
      status: 'Optimal',
      advice: 'True bandwidth aggregation for mission-critical tasks.',
      kit_type: 'internet',
      product_name: 'Bonded Stack Internet Kit',
      product_description: 'True packet-level bonding. Speedify + Dual CPE Pro hardware.',
      component_specs: [{ role: 'network', name: 'Bonded Stack Internet Kit', quantity: 1, specs: { watts: 20 } }],
    },
    tags: ['internet', 'kit', 'tier-c'],
    price: 310000,
  },
  { id: 'p_int_1', name: 'Single CPE Upgrade (ZTE MC888)', description: 'Immediate speed improvement with zero plan change. Superior antenna and radio pull dramatically more signal.', type: 'standalone', tags: ['internet', 'tier-a', 'flagship'], price: 110000 },
  { id: 'p_int_4', name: 'GL.iNet Spitz AX All-in-One', description: 'Everything integrated: 5G modem, dual SIM, load balancing, WiFi 6, and VPN.', type: 'standalone', tags: ['internet', 'tier-b', 'flagship'], price: 160000 },
  { id: 'p_h_1', name: 'Kulpower 100W Mono Panel', description: 'Exceptional low irradiance performance. PID resistant.', type: 'standalone', tags: ['panel', 'solar', 'flagship'], price: 32000 },
  { id: 'p_h_2', name: '9Solar 190W Mono Panel', description: 'Radically reduced string mismatch losses. Built-in bypass diode.', type: 'standalone', tags: ['panel', 'solar', 'flagship'], price: 45000 },
  { id: 'p_h_3', name: 'Kulpower 340W Mono Panel', description: "Industry's lowest thermal co-efficient. High-yield upgrade.", type: 'standalone', tags: ['panel', 'solar', 'flagship'], price: 70000 },
  { id: 'p_h_4', name: 'PowMr 50A LiFePO4 Battery', description: 'Massive 640Wh usable capacity. Grade A cells.', type: 'standalone', tags: ['battery', 'solar', 'flagship'], price: 110000 },
  { id: 'p_h_5', name: 'Taico 12V 100Ah LiFePO4', description: 'Smart Bluetooth Monitoring. Integrated BMS.', type: 'standalone', tags: ['battery', 'solar'], price: 210000 },
  { id: 'p_h_6', name: 'Cworth 12V 100Ah LiFePO4', description: 'Modular design. DIY-friendly expansion.', type: 'standalone', tags: ['battery', 'solar'], price: 230000 },
  { id: 'p_h_7', name: 'Huawei B818-263 4G+ Router', description: 'High-performance 4G+ router. Tier A.', type: 'standalone', tags: ['internet', 'tier-a'], price: 85000 },
  { id: 'p_h_8', name: 'ZTE MC888 5G Router', description: '5G Indoor CPE, WiFi 6. Tier A.', type: 'standalone', tags: ['internet', 'tier-a'], price: 95000 },
  { id: 'p_h_9', name: 'Kulpower 250W Mono Panel', description: 'High-efficiency monocrystalline panel.', type: 'standalone', tags: ['panel', 'solar'], price: 50000 },
  { id: 'p_h_10', name: '9Solar 450W Mono Panel', description: 'High-yield upgrade for heavy-duty setups.', type: 'standalone', tags: ['panel', 'solar'], price: 85000 },
  { id: 'p_h_11', name: 'Taico 12V 200Ah LiFePO4', description: 'High capacity lithium storage.', type: 'standalone', tags: ['battery', 'solar'], price: 375000 },
  { id: 'p_h_12', name: 'Cworth 12V 200Ah LiFePO4', description: 'High capacity modular lithium storage.', type: 'standalone', tags: ['battery', 'solar'], price: 390000 },
];

export const seedHardware = [
  { id: 'h1', type: 'panel', tags: ['flagship', 'solar', 'panel'], description: 'Exceptional low irradiance performance. PID resistant.', data: { name: 'Kulpower 100W Mono Crystalline Panel', watts: 100, voc: 22.5, isc: 5.8, price: 32000 } },
  { id: 'h2', type: 'panel', tags: ['flagship', 'solar', 'panel'], description: 'Radically reduced string mismatch losses. Built-in bypass diode.', data: { name: '9Solar 190W Mono Crystalline Panel (39 Cells)', watts: 190, voc: 24.2, isc: 10.1, price: 45000 } },
  { id: 'h3', type: 'panel', tags: ['flagship', 'solar', 'panel'], description: "Industry's lowest thermal co-efficient. High-yield upgrade.", data: { name: 'Kulpower 340W Mono Crystalline Panel', watts: 340, voc: 41.5, isc: 10.5, price: 70000 } },
  { id: 'h_p_4', type: 'panel', tags: ['solar', 'panel'], description: 'High-yield upgrade for heavy-duty setups.', data: { name: 'Kulpower 450W Mono Crystalline Panel', watts: 450, voc: 49.5, isc: 11.5, price: 85000 } },
  { id: 'h_p_5', type: 'panel', tags: ['solar', 'panel'], description: 'High-efficiency monocrystalline panel.', data: { name: '9Solar 330W Mono Crystalline Panel', watts: 330, voc: 40.5, isc: 10.2, price: 73000 } },
  { id: 'h_p_6', type: 'panel', tags: ['solar', 'panel'], description: 'High-efficiency monocrystalline panel.', data: { name: '9Solar 430W Mono Crystalline Panel', watts: 430, voc: 49.2, isc: 11.1, price: 95000 } },
  { id: 'h_p_7', type: 'panel', tags: ['solar', 'panel'], description: 'High-efficiency monocrystalline panel.', data: { name: '9Solar 600W Mono Crystalline Panel', watts: 600, voc: 54.5, isc: 13.8, price: 105000 } },
  { id: 'h4', type: 'battery', tags: ['flagship', 'solar', 'battery'], description: 'Massive 640Wh usable capacity. Grade A cells.', data: { name: 'PowMr 50A LiFePO4 Expansion Battery', voltage: 12.8, capacity_ah: 50, type: 'lithium', min_c_rate: 0.1, price: 110000 } },
  { id: 'h11', type: 'battery', tags: ['solar', 'battery', 'lithium'], description: 'Smart Bluetooth Monitoring. Integrated BMS.', data: { name: 'Taico 12V 100Ah LiFePO4', voltage: 12.8, capacity_ah: 100, type: 'lithium', min_c_rate: 0.1, price: 210000 } },
  { id: 'h_b_2', type: 'battery', tags: ['solar', 'battery', 'lithium'], description: 'High capacity lithium storage.', data: { name: 'Taico 12V 200Ah LiFePO4', voltage: 12.8, capacity_ah: 200, type: 'lithium', min_c_rate: 0.1, price: 375000 } },
  { id: 'h12', type: 'battery', tags: ['solar', 'battery', 'lithium'], description: 'Modular design. DIY-friendly expansion.', data: { name: 'Cworth 12V 100Ah LiFePO4', voltage: 12.8, capacity_ah: 100, type: 'lithium', min_c_rate: 0.1, price: 230000 } },
  { id: 'h_b_4', type: 'battery', tags: ['solar', 'battery', 'lithium'], description: 'High capacity modular lithium storage.', data: { name: 'Cworth 12V 200Ah LiFePO4', voltage: 12.8, capacity_ah: 200, type: 'lithium', min_c_rate: 0.1, price: 390000 } },
  { id: 'h_p_8', type: 'panel', tags: ['solar', 'panel'], description: 'High-efficiency monocrystalline panel.', data: { name: 'Kulpower 250W Mono Crystalline Panel', watts: 250, voc: 30.5, isc: 10.8, price: 50000 } },
  { id: 'h_p_9', type: 'panel', tags: ['solar', 'panel'], description: 'High-yield upgrade for heavy-duty setups.', data: { name: '9Solar 450W Mono Crystalline Panel', watts: 450, voc: 49.5, isc: 11.5, price: 85000 } },
  { id: 'h_p_10', type: 'panel', tags: ['solar', 'panel'], description: 'Premium high-wattage panel.', data: { name: '9Solar 550W Mono Crystalline Panel', watts: 550, voc: 49.9, isc: 14, price: 115000 } },
  { id: 'h_p_11', type: 'panel', tags: ['solar', 'panel'], description: 'Ultra high-efficiency panel.', data: { name: '9Solar 600W Mono Crystalline Panel', watts: 600, voc: 51.5, isc: 14.6, price: 135000 } },
  { id: 'h_b_5', type: 'battery', tags: ['solar', 'battery', 'lithium'], description: 'High capacity lithium storage.', data: { name: 'Taico 12V 200Ah LiFePO4', voltage: 12.8, capacity_ah: 200, type: 'lithium', min_c_rate: 0.1, price: 375000 } },
  { id: 'h_b_6', type: 'battery', tags: ['solar', 'battery', 'lithium'], description: 'High capacity modular lithium storage.', data: { name: 'Cworth 12V 200Ah LiFePO4', voltage: 12.8, capacity_ah: 200, type: 'lithium', min_c_rate: 0.1, price: 390000 } },
  { id: 'h5', type: 'accessory', tags: ['flagship', 'solar', 'accessory'], description: 'Premium wiring for flexible panel connectivity. Weatherproof.', data: { name: 'Heavy-Duty Solar Extension Cables', price: 4500 } },
  { id: 'h6', type: 'powerstation', tags: ['flagship', 'portable', 'pure-sine'], description: 'True plug-and-play Setup in a Box.', data: { name: 'SolarOne A300', capacity_wh: 390, max_output_w: 300, max_pv_input_w: 250, price: 185000, battery_type: 'lithium', inverter_type: 'pure-sine', system_vdc: 12, max_charge_amps: 20, cc_type: 'mppt', cc_max_voc: 50, cc_max_amps: 20, max_parallel_units: 1, battery_voltage: 12.8, capacity_ah: 30, min_c_rate: 0.1 } },
  { id: 'h7', type: 'powerstation', tags: ['flagship', 'pro', 'pure-sine'], description: 'Whole-house power without the installation.', data: { name: 'SolarOne A500 Pro', capacity_wh: 600, max_output_w: 500, max_pv_input_w: 350, price: 300000, battery_type: 'lithium', inverter_type: 'pure-sine', system_vdc: 12, max_charge_amps: 40, cc_type: 'mppt', cc_max_voc: 50, cc_max_amps: 30, max_parallel_units: 1, battery_voltage: 12.8, capacity_ah: 50, min_c_rate: 0.1 } },
  { id: 'h8', type: 'powerstation', tags: ['budget', 'student', 'pure-sine'], description: 'Compact student power box.', data: { name: 'Itel Energy iESS 320T', capacity_wh: 320, max_output_w: 130, max_pv_input_w: 200, price: 140000, battery_type: 'lithium', inverter_type: 'pure-sine', system_vdc: 12, max_charge_amps: 10, cc_type: 'pwm', cc_max_voc: 25, cc_max_amps: 10, max_parallel_units: 1, battery_voltage: 12.8, capacity_ah: 25, min_c_rate: 0.1 } },
  { id: 'h9', type: 'powerstation', tags: ['mid-range', 'modified-sine'], description: 'Affordable backup power.', data: { name: '500W Generic Powerstation', capacity_wh: 600, max_output_w: 500, max_pv_input_w: 350, price: 265000, battery_type: 'lithium', inverter_type: 'modified-sine', system_vdc: 12, max_charge_amps: 30, cc_type: 'pwm', cc_max_voc: 30, cc_max_amps: 20, max_parallel_units: 1, battery_voltage: 12.8, capacity_ah: 50, min_c_rate: 0.1 } },
  { id: 'h10', type: 'powerstation', tags: ['pro', 'high-capacity'], description: 'High capacity studio power.', data: { name: 'Itel 1000W Powerstation', capacity_wh: 1000, max_output_w: 500, max_pv_input_w: 450, price: 340000, battery_type: 'lithium', inverter_type: 'pure-sine', system_vdc: 12, max_charge_amps: 50, cc_type: 'mppt', cc_max_voc: 60, cc_max_amps: 40, max_parallel_units: 1, battery_voltage: 12.8, capacity_ah: 80, min_c_rate: 0.1 } },
  { id: 'h_ps_1', type: 'powerstation', tags: ['premium', 'high-capacity'], description: 'Industry leading portable power.', data: { name: 'EcoFlow Delta Pro', capacity_wh: 3600, max_output_w: 3600, max_pv_input_w: 1600, price: 2850000, battery_type: 'lithium', inverter_type: 'pure-sine', system_vdc: 48, max_charge_amps: 80, cc_type: 'mppt', cc_max_voc: 150, cc_max_amps: 30, max_parallel_units: 1, battery_voltage: 48, capacity_ah: 75, min_c_rate: 0.1 } },
  { id: 'h_ps_2', type: 'powerstation', tags: ['premium', 'expandable'], description: 'Reliable backup for home and travel.', data: { name: 'Bluetti AC200MAX', capacity_wh: 2048, max_output_w: 2200, max_pv_input_w: 900, price: 1650000, battery_type: 'lithium', inverter_type: 'pure-sine', system_vdc: 48, max_charge_amps: 40, cc_type: 'mppt', cc_max_voc: 145, cc_max_amps: 15, max_parallel_units: 1, battery_voltage: 48, capacity_ah: 40, min_c_rate: 0.1 } },
  { id: 'h_ps_3', type: 'powerstation', tags: ['compact', 'budget'], description: 'Essential power for small electronics.', data: { name: 'Itel 500W Powerstation', capacity_wh: 512, max_output_w: 500, max_pv_input_w: 200, price: 245000, battery_type: 'lithium', inverter_type: 'pure-sine', system_vdc: 12, max_charge_amps: 20, cc_type: 'mppt', cc_max_voc: 30, cc_max_amps: 15, max_parallel_units: 1, battery_voltage: 12.8, capacity_ah: 40, min_c_rate: 0.1 } },
  { id: 'h_i_1', type: 'internet', tags: ['internet', 'tier-a'], description: '4G LTE Cat19 Indoor CPE.', data: { name: 'Huawei B818-263', default_watts: 15, price: 85000 } },
  { id: 'h_i_2', type: 'internet', tags: ['internet', 'tier-a'], description: '5G Indoor CPE, WiFi 6.', data: { name: 'ZTE MC888', default_watts: 20, price: 95000 } },
  { id: 'h_i_3', type: 'internet', tags: ['internet', 'tier-a'], description: '5G Indoor CPE, WiFi 6 (upgraded).', data: { name: 'ZTE MC888 Pro', default_watts: 25, price: 120000 } },
  { id: 'h_i_4', type: 'internet', tags: ['internet', 'tier-a'], description: '5G Indoor/Outdoor Hybrid CPE.', data: { name: 'Huawei CPE Pro 2', default_watts: 20, price: 70000 } },
  { id: 'h_i_5', type: 'internet', tags: ['internet', 'tier-a'], description: 'Budget 4G Indoor CPE.', data: { name: 'Cudy LT500', default_watts: 12, price: 45000 } },
  { id: 'h_i_6', type: 'internet', tags: ['internet', 'tier-b'], description: 'Multi-WAN Load Balancing Router.', data: { name: 'TP-Link ER605 (V2)', default_watts: 10, price: 75000 } },
  { id: 'h_i_7', type: 'internet', tags: ['internet', 'tier-b'], description: 'Professional Multi-WAN Load Balancing Router.', data: { name: 'TP-Link ER7206', default_watts: 15, price: 90000 } },
  { id: 'h_i_8', type: 'internet', tags: ['internet', 'tier-b'], description: 'All-in-One Dual-SIM 5G Router with WiFi 6.', data: { name: 'GL.iNet Spitz AX (GL-X3000)', default_watts: 20, price: 160000 } },
  { id: 'h_i_9', type: 'internet', tags: ['internet', 'tier-b'], description: 'Travel Router with Multi-WAN.', data: { name: 'GL.iNet Slate AX (GL-AXT1800)', default_watts: 10, price: 75000 } },
  { id: 'h_i_10', type: 'internet', tags: ['internet', 'tier-b'], description: 'Budget Multi-WAN Load Balancer.', data: { name: 'Cudy WR2100', default_watts: 10, price: 35000 } },
  { id: 'h_i_11', type: 'internet', tags: ['internet', 'tier-c'], description: 'Hardware Bonding Router.', data: { name: 'Pepwave MAX BR1 Mini', default_watts: 15, price: 350000 } },
];
